### ISSUE TITLE
running error with "Bus error: nonexistent physical address"

### ISSUE THREAD

**Issue by Emerald01** [huggingface/transformers-bloom-inference#16] opened 2022-10-06 20:09 UTC
Hello,
Thank you for this interesting script. I am trying to test the deepspeed inference, but it gives me such error (I am just using a small bloom model to start with)
Any hint on what is going wrong right here? Look like some nccl issue

```
transformers-bloom-inference# deepspeed --num_gpus 8 bloom-inference-scripts/bloom-ds-inference.py --name bigscience/bloom-3b --benchmark --batch_size 8

[2022-10-06 20:04:34,388] [WARNING] [runner.py:178:fetch_hostfile] Unable to find hostfile, will proceed with training with local resources only.
[2022-10-06 20:04:35,202] [INFO] [runner.py:504:main] cmd = /opt/conda/bin/python3.8 -u -m deepspeed.launcher.launch --world_info=eyJsb2NhbGhvc3QiOiBbMCwgMSwgMiwgMywgNCwgNSwgNiwgN119 --master_addr=127.0.0.1 --master_port=29500 bloom-inference-scripts/bloom-ds-inference.py --name bigscience/bloom-3b --benchmark --batch_size 8
[2022-10-06 20:04:37,529] [INFO] [launch.py:129:main] 0 NCCL_VERSION=2.12.12
[2022-10-06 20:04:37,529] [INFO] [launch.py:136:main] WORLD INFO DICT: {'localhost': [0, 1, 2, 3, 4, 5, 6, 7]}
[2022-10-06 20:04:37,529] [INFO] [launch.py:142:main] nnodes=1, num_local_procs=8, node_rank=0
[2022-10-06 20:04:37,529] [INFO] [launch.py:155:main] global_rank_mapping=defaultdict(<class 'list'>, {'localhost': [0, 1, 2, 3, 4, 5, 6, 7]})
[2022-10-06 20:04:37,529] [INFO] [launch.py:156:main] dist_world_size=8
[2022-10-06 20:04:37,530] [INFO] [launch.py:158:main] Setting CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7
[2022-10-06 20:04:40,295] [INFO] [comm.py:633:init_distributed] Initializing TorchBackend in DeepSpeed with backend nccl
*** Loading the model bigscience/bloom-3b
[2022-10-06 20:04:42,571] [INFO] [utils.py:827:see_memory_usage] pre-from-pretrained
[2022-10-06 20:04:42,572] [INFO] [utils.py:828:see_memory_usage] MA 0.0 GB         Max_MA 0.0 GB         CA 0.0 GB         Max_CA 0 GB 
[2022-10-06 20:04:42,572] [INFO] [utils.py:836:see_memory_usage] CPU Virtual Memory:  used = 8.58 GB, percent = 1.3%
[2022-10-06 20:04:42,707] [INFO] [utils.py:827:see_memory_usage] post-from-pretrained
[2022-10-06 20:04:42,707] [INFO] [utils.py:828:see_memory_usage] MA 0.0 GB         Max_MA 0.0 GB         CA 0.0 GB         Max_CA 0 GB 
[2022-10-06 20:04:42,708] [INFO] [utils.py:836:see_memory_usage] CPU Virtual Memory:  used = 8.58 GB, percent = 1.3%
[2022-10-06 20:04:42,821] [INFO] [utils.py:827:see_memory_usage] post-init-ds-zero-init
[2022-10-06 20:04:42,822] [INFO] [utils.py:828:see_memory_usage] MA 0.0 GB         Max_MA 0.0 GB         CA 0.0 GB         Max_CA 0 GB 
[2022-10-06 20:04:42,822] [INFO] [utils.py:836:see_memory_usage] CPU Virtual Memory:  used = 8.58 GB, percent = 1.3%
Fetching 8 files: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:00<00:00, 22504.65it/s]
Fetching 8 files: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:00<00:00, 18893.26it/s]
Fetching 8 files: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:00<00:00, 22177.42it/s]
Fetching 8 files: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:00<00:00, 23933.26it/s]
Fetching 8 files: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:00<00:00, 23780.60it/s]
Fetching 8 files: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:00<00:00, 24672.38it/s]
[2022-10-06 20:04:42,938] [INFO] [utils.py:827:see_memory_usage] pre-ds-inference-init
[2022-10-06 20:04:42,939] [INFO] [utils.py:828:see_memory_usage] MA 0.0 GB         Max_MA 0.0 GB         CA 0.0 GB         Max_CA 0 GB 
[2022-10-06 20:04:42,939] [INFO] [utils.py:836:see_memory_usage] CPU Virtual Memory:  used = 8.73 GB, percent = 1.3%
Fetching 8 files: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:00<00:00, 21931.00it/s]
Fetching 8 files: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:00<00:00, 22595.58it/s]
Fetching 8 files: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:00<00:00, 22779.66it/s]
[sfr-pod-a100-x8-tian-lan:4200 :0:5033] Caught signal 7 (Bus error: nonexistent physical address)
==== backtrace (tid:   5033) ====
 0 0x0000000000014420 __funlockfile()  ???:0
 1 0x000000000018bb41 __nss_database_lookup()  ???:0
 2 0x000000000006929c ncclGroupEnd()  ???:0
 3 0x000000000005e36d ncclGroupEnd()  ???:0
 4 0x0000000000008609 start_thread()  ???:0
 5 0x000000000011f133 clone()  ???:0
=================================
[2022-10-06 20:04:59,604] [INFO] [launch.py:286:sigkill_handler] Killing subprocess 4195
[2022-10-06 20:04:59,779] [INFO] [launch.py:286:sigkill_handler] Killing subprocess 4196
[2022-10-06 20:04:59,952] [INFO] [launch.py:286:sigkill_handler] Killing subprocess 4197
[2022-10-06 20:05:00,125] [INFO] [launch.py:286:sigkill_handler] Killing subprocess 4198
[2022-10-06 20:05:00,299] [INFO] [launch.py:286:sigkill_handler] Killing subprocess 4199
[2022-10-06 20:05:00,472] [INFO] [launch.py:286:sigkill_handler] Killing subprocess 4200
[2022-10-06 20:05:00,472] [INFO] [launch.py:286:sigkill_handler] Killing subprocess 4201
[2022-10-06 20:05:00,645] [INFO] [launch.py:286:sigkill_handler] Killing subprocess 4202
[2022-10-06 20:05:00,818] [ERROR] [launch.py:292:sigkill_handler] ['/opt/conda/bin/python3.8', '-u', 'bloom-inference-scripts/bloom-ds-inference.py', '--local_rank=7', '--name', 'bigscience/bloom-3b', '--benchmark', '--batch_size', '8'] exits with return code = -7
```

**Comment by Emerald01** [comment] 2022-10-06 21:31
I find the main error is that it runs out of shared memory quickly at `/dev/shm`, not sure if the multiprocessing shows some inefficiency on this

**Comment by mayank31398** [comment] 2022-10-08 11:26
Does it work on 1 GPU?
You don't need 8 GPUs for 3 billion

**Comment by felifri** [comment] 2022-12-29 12:12
I get the same error. However, if I reduce to 4 GPUs it does not appear. If I want to run the bloom176gb model, I get the error again as I have to use all 8 GPUs.

**Comment by mayank31398** [comment] 2022-12-29 12:21
Its not easy to debug this @felifri.
I believe this is a hardware related thing. Can you open an issue in DeepSpeed's github?

I have tried 64 GPUs (8 different servers) and have not encountered this issue.

**Comment by mayank31398** [comment] 2023-02-18 21:52
Closing this since its too old. Feel free to re-open

**Closed by mayank31398** 2023-02-18 21:52 UTC

**Comment by felifri** [comment] 2023-02-19 11:11
I opened a DeepSpeed bug thread, for those interested and related 
https://github.com/microsoft/DeepSpeed/issues/2693

**Comment by hijkzzz** [comment] 2023-03-17 07:40
I got the same issue with ColossalAI Zero2

**Comment by ybdesire** [comment] 2023-11-24 10:15
The error shows when running deepspeed at my docker image, root cause is the same as /dev/shm has low memory .  And it can be fixed by `docker run -it --shm-size 6G image_name  /bin/bash`
