### ISSUE TITLE
Why does ds-inference int8 run slower than ds-inference fp16?

### ISSUE THREAD

**Issue by DominickZhang** [huggingface/transformers-bloom-inference#79] opened 2023-04-19 15:11 UTC
Hi,

I am confused about the performance of ds-inference int8. I think it should be at least as fast as ds-inference fp16, but it turns out to be slower. Could you help with my problem? Many thanks!

<img width="695" alt="image" src="https://user-images.githubusercontent.com/16048179/233118813-cb0bba2a-83ff-4d47-b060-cb7e87ad887e.png">

**Comment by mayank31398** [comment] 2023-04-19 17:04
Hi, this is expected behaviour.
This is because int8 on ZeRO-Quant (DeepSpeed) is not using CUDA kernels yet.
You might want to ask about this support in the DeepSpeed repo :)

**Comment by DominickZhang** [comment] 2023-04-20 02:08
> Hi, this is expected behaviour. This is because int8 on ZeRO-Quant (DeepSpeed) is not using CUDA kernels yet. You might want to ask about this support in the DeepSpeed repo :)

Thanks a lot! Now I am clear! 

I just referred to an official [website](https://www.microsoft.com/en-us/research/blog/deepspeed-accelerating-large-scale-model-inference-and-training-via-system-optimizations-and-compression/), where the mixture of quantization (MoQ) is introduced. MoQ involves high-performance INT8 inference kernels in DeepSpeed. I am wondering why we use ZeRO-Quant here instead of MoQ?

**Comment by mayank31398** [comment] 2023-05-10 01:39
Haven't looked into MoQ.
Closing this for now :)

**Closed by mayank31398** 2023-05-10 01:39 UTC
